# .github/workflows/deploy.yml
name: Deploy to NAS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # Docker now handles the entire build process, including Tailwind!
      - name: Build and Deploy with Docker Compose
        run: |
          docker compose build --no-cache
          docker compose up -d --force-recreate