name: Deploy to Server

# This workflow runs on every push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to your project directory on the server
            cd /volume1/docker/portainer/compose/44

            # Pull the latest code from GitHub
            git pull

            # Rebuild and restart the container
            sudo docker compose up -d --build