# .github/workflows/deploy.yml
name: Deploy to NAS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build and Deploy with Docker Compose
        run: |
          docker compose build --no-cache
          docker compose up -d --force-recreate
      
      - name: Purge Cloudflare CSS Cache for WWW
        if: success()
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"files":["https://www.${{ secrets.CLOUDFLARE_DOMAIN }}/css/output.css"]}'